[package]
version = "0.1.0"
name = "prover-program"
edition = "2021"

[dependencies]
sp1-zkvm = "3.4.0"
hyle-contract-sdk = { git = "https://github.com/hyle-org/hyle" }
prover-lib = { path = "../lib" }