[package]
version = "0.1.0"
name = "prover-program"
edition = "2021"

[dependencies]
sp1-zkvm = "3.0.0-rc4"
prover-lib = { path = "../lib" }
hyle_contract = { git = "https://github.com/hyle-org/hyle-cosmos.git", branch = "main" }